baseURL = 'https://adamsdphilnotes.netlify.app/'
languageCode = 'en-us'
title = 'Education in the Hellenistic World'

theme = "hyde"

[Menus]
  main = [
      {Name = "– Research Updates for DPhil Meetings", URL = "https://adamsdphilnotes.netlify.app/posts/Meeting-Updates/"},
      {Name = "– DPhil Meeting Notes", URL = "https://adamsdphilnotes.netlify.app/posts/dphil-meetings-with-stevens/"},
      {Name = "– Current Research Tasks", URL = "https://adamsdphilnotes.netlify.app/posts/current-research-tasks/"},
      {Name = "– Working Bibliography", URL = "https://1drv.ms/w/s!AtFZ4ElDbRkTijFTEK2TMet9-JhG"}
  ]

  [params]
  description = "Adam's DPhil Research Notes"

[[module.mounts]]
source = "images"
target = "assets/images"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 6
    ordered = true
    startLevel = 2

disqusShortname = "adamburge"