baseURL = ''
languageCode = 'en-us'
title = 'DPhil Research Notes'

theme = "hyde"

[Menus]
  main = [
      {Name = "Thing One", URL = "https://github.com/username/"},
      {Name = "Thing Two", URL = "https://www.linkedin.com/in/username/"}
  ]

  [params]
  description = " "

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true